// GTA San Andreas Main Theme — dari MIDI asli
// BPM 95 | 11 track | ~77.7 detik
// T0=Drum T1=Bass T2=Guitar T3=Piano(chord) T4=Piano(bell)
// T5=Sax(violin) T6=Sax(cello) T7=Flute(metal) T8=Piano(wood)
// T9=Guitar2 T10=Flute(sfx)

#![recursion_limit = "4096"]

use f_audio::*;

fn main() {
    println!("[INFO] Merender GTA San Andreas Main Theme...");

    audio!(lagu, {

        drums {
            beat => {
                volume: 85,
                once {
                    "kick", long(630),
                    "tom", long(314),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat_open", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat_open", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat_open", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat_open", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat_open", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat_open", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat_open", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat_open", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat_open", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat_open", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat_open", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat_open", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat_open", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat_open", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat_open", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat_open", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat_open", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat_open", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat_open", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat_open", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat_open", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat_open", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat_open", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat_open", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat_open", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat_open", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(315),
                    "hat", long(315),
                    "snare", long(315),
                    "hat", long(314),
                    "hat", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat_open", long(315),
                    "snare", long(315),
                    "hat", long(315),
                    "hat_open", long(314),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(630),
                    "hat", long(314),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(315),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat", long(314),
                    "snare", long(314),
                    "hat", long(314),
                    "hat", long(315),
                    "kick", long(631),
                    "hat", long(315),
                    "hat_open", long(314),
                    "snare", long(314),
                    "hat", long(314),
                }
            }
        },

        bass {
            line => {
                volume: 88,
                once {
                    "G2", long(314),
                    "D2", long(314),
                    "F1", long(314),
                    "G1", long(631),
                    gap(790),
                    "G1", long(157),
                    "G1", long(315),
                    gap(1264),
                    "Bb1", long(631),
                    "Ab2", long(314),
                    "G2", long(314),
                    "D2", long(315),
                    "F1", long(315),
                    "G1", long(630),
                    gap(791),
                    "G1", long(157),
                    "G1", long(314),
                    gap(1265),
                    "Bb1", long(630),
                    "Ab2", long(315),
                    "G2", long(315),
                    "D2", long(315),
                    "F1", long(314),
                    "G1", long(630),
                    gap(791),
                    "G1", long(156),
                    "G1", long(314),
                    gap(1265),
                    "Bb1", long(630),
                    "Ab2", long(315),
                    "G2", long(314),
                    "D2", long(314),
                    "F1", long(314),
                    "G1", long(631),
                    gap(790),
                    "G1", long(157),
                    "G1", long(315),
                    gap(1264),
                    "Bb1", long(630),
                    "Ab2", long(314),
                    "G2", long(314),
                    "D2", long(315),
                    "F1", long(315),
                    "G1", long(630),
                    gap(791),
                    "G1", long(157),
                    "G1", long(314),
                    gap(1265),
                    "Bb1", long(630),
                    "Ab2", long(315),
                    "G2", long(315),
                    "D2", long(314),
                    "F1", long(314),
                    "G1", long(630),
                    gap(791),
                    "G1", long(156),
                    "G1", long(314),
                    gap(1264),
                    "Bb1", long(631),
                    "Ab2", long(315),
                    "G2", long(314),
                    "D2", long(314),
                    "F1", long(315),
                    "G1", long(630),
                    gap(791),
                    "G1", long(157),
                    "G1", long(315),
                    gap(1264),
                    "Bb1", long(630),
                    "Ab2", long(314),
                    "G2", long(315),
                    "D2", long(315),
                    "F1", long(315),
                    "G1", long(630),
                    gap(791),
                    "G1", long(156),
                    "G1", long(314),
                    gap(1265),
                    "Bb1", long(630),
                    "Ab2", long(315),
                    "G2", long(315),
                    "D2", long(314),
                    "F1", long(314),
                    "G1", long(631),
                    gap(791),
                    "G1", long(156),
                    "G1", long(315),
                    gap(1264),
                    "Bb1", long(631),
                    "Ab2", long(314),
                    "G2", long(314),
                    "D2", long(314),
                    "F1", long(315),
                    "G1", long(630),
                    gap(791),
                    "G1", long(157),
                    "G1", long(315),
                    gap(1264),
                    "Bb1", long(630),
                    "Ab2", long(314),
                    "G2", long(315),
                    "D2", long(315),
                    "F1", long(314),
                    "G1", long(630),
                    gap(791),
                    "G1", long(156),
                    "G1", long(314),
                    gap(1265),
                    "Bb1", long(630),
                    "Ab2", long(315),
                    "G2", long(315),
                    "D2", long(314),
                    "F1", long(314),
                    "G1", long(631),
                    gap(790),
                    "G1", long(157),
                    "G1", long(315),
                    gap(1264),
                    "Bb1", long(631),
                    "Ab2", long(314),
                    "G2", long(314),
                    "D2", long(315),
                    "F1", long(315),
                    "G1", long(630),
                    gap(791),
                    "G1", long(157),
                    "G1", long(314),
                    gap(1265),
                    "Bb1", long(630),
                    "Ab2", long(314),
                    "G2", long(315),
                    "D2", long(315),
                    "F1", long(314),
                    "G1", long(630),
                    gap(791),
                    "G1", long(156),
                    "G1", long(314),
                    gap(1265),
                    "Bb1", long(630),
                    "Ab2", long(315),
                    "G2", long(314),
                    "D2", long(314),
                    "F1", long(314),
                    "G1", long(631),
                    gap(790),
                    "G1", long(157),
                    "G1", long(315),
                    gap(1264),
                    "Bb1", long(630),
                    "Ab2", long(314),
                    "G2", long(314),
                    gap(633),
                    "G1", long(314),
                }
            }
        },

        guitar {
            riff => {
                volume: 70,
                preset: "acoustic_single",
                once {
                    gap(1895),
                    "Bb4", long(156),
                    "G4", long(156),
                    "A4", long(156),
                    "Gb4", long(156),
                    "Bb4", long(156),
                    "G4", long(156),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(157),
                    "Gb4", long(157),
                    "Bb4", long(157),
                    "G4", long(157),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(156),
                    "Gb4", long(156),
                    "Bb4", long(156),
                    "G4", long(156),
                    gap(4581),
                    "Bb4", long(156),
                    "G4", long(156),
                    "A4", long(156),
                    "Gb4", long(156),
                    "Bb4", long(157),
                    "G4", long(157),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(157),
                    "Gb4", long(157),
                    "Bb4", long(157),
                    "G4", long(157),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(156),
                    "Gb4", long(156),
                    "Bb4", long(156),
                    "G4", long(156),
                    gap(4581),
                    "Bb4", long(156),
                    "G4", long(156),
                    "A4", long(157),
                    "Gb4", long(157),
                    "Bb4", long(157),
                    "G4", long(157),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(157),
                    "Gb4", long(157),
                    "Bb4", long(157),
                    "G4", long(157),
                    gap(4580),
                    "Bb4", long(156),
                    "G4", long(156),
                    "A4", long(156),
                    "Gb4", long(156),
                    "Bb4", long(156),
                    "G4", long(156),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(157),
                    "Gb4", long(157),
                    "Bb4", long(157),
                    "G4", long(157),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(157),
                    "Gb4", long(157),
                    "Bb4", long(157),
                    "G4", long(157),
                    gap(4580),
                    "Bb4", long(156),
                    "G4", long(156),
                    "A4", long(156),
                    "Gb4", long(156),
                    "Bb4", long(156),
                    "G4", long(156),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(157),
                    "Gb4", long(157),
                    "Bb4", long(157),
                    "G4", long(157),
                    gap(4580),
                    "Bb4", long(157),
                    "G4", long(157),
                    "A4", long(157),
                    "Gb4", long(157),
                    "Bb4", long(156),
                    "G4", long(156),
                    gap(4581),
                    "Bb4", long(156),
                    "G4", long(156),
                    "A4", long(156),
                    "Gb4", long(156),
                    "Bb4", long(157),
                    "G4", long(157),
                }
            },
            riff2 => {
                volume: 67,
                preset: "acoustic_single",
                once {
                    gap(48000),
                    "G3", long(315),
                    "G4", long(156),
                    "D5", long(314),
                    "G4", long(156),
                    "Db5", long(315),
                    "G4", long(157),
                    "C5", long(315),
                    "G4", long(157),
                    "Bb4", long(314),
                    gap(317),
                    "Bb4", long(1262),
                    "G4", long(1262),
                    gap(1265),
                    "G3", long(314),
                    "G4", long(156),
                    "D5", long(315),
                    "G4", long(157),
                    "Db5", long(315),
                    "G4", long(156),
                    "C5", long(314),
                    "G4", long(156),
                    "Bb4", long(315),
                    gap(317),
                    "Bb4", long(1262),
                    "G4", long(1262),
                    gap(11370),
                    "G3", long(314),
                    "G4", long(157),
                    "D5", long(315),
                    "G4", long(157),
                    "Db5", long(314),
                    "G4", long(156),
                    "C5", long(314),
                    "G4", long(157),
                    "Bb4", long(315),
                    gap(317),
                    "Bb4", long(1262),
                    "G4", long(1262),
                    gap(1264),
                    "G3", long(315),
                    "G4", long(157),
                    "D5", long(314),
                    "G4", long(156),
                    "Db5", long(314),
                    "G4", long(157),
                    "C5", long(315),
                    "G4", long(157),
                    "Bb4", long(314),
                    gap(318),
                    "Bb4", long(314),
                    "G4", long(314),
                }
            }
        },

        piano {
            chords => {
                volume: 70,
                once {
                    gap(632),
                    "Bb5", long(1261),
                    "D5", long(1261),
                    "G5", long(1261),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2527),
                    "C6", long(631),
                    "Eb5", long(631),
                    "G5", long(631),
                    gap(633),
                    "Bb5", long(1261),
                    "D5", long(1261),
                    "G5", long(1261),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2527),
                    "C6", long(631),
                    "Eb5", long(631),
                    "G5", long(631),
                    gap(632),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2527),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2527),
                    "C6", long(631),
                    "Eb5", long(631),
                    "G5", long(631),
                    gap(633),
                    "Bb5", long(1261),
                    "D5", long(1261),
                    "G5", long(1261),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                    gap(2527),
                    "C6", long(631),
                    "Eb5", long(631),
                    "G5", long(631),
                    gap(633),
                    "Bb5", long(1261),
                    "D5", long(1261),
                    "G5", long(1261),
                    gap(2528),
                    "C6", long(630),
                    "Eb5", long(630),
                    "G5", long(630),
                    gap(633),
                    "Bb5", long(1262),
                    "D5", long(1262),
                    "G5", long(1262),
                }
            },
            bell => {
                volume: 65,
                once {
                    gap(3158),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    gap(3160),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    gap(3159),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    gap(3159),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    gap(3159),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    gap(3159),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    gap(3159),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    gap(3159),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    gap(3159),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    gap(3160),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    gap(3159),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    gap(3159),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    gap(3160),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    gap(3159),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    gap(3159),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(157),
                    "B5", long(156),
                    "B5", long(156),
                    "B5", long(156),
                }
            },
            wood => {
                volume: 60,
                once {
                    gap(46105),
                    "E5", long(631),
                    "F5", long(630),
                    "E5", long(631),
                    gap(3159),
                    "E5", long(630),
                    "F5", long(630),
                    "E5", long(630),
                }
            }
        },

        sax {
            violin => {
                volume: 95,
                once {
                    gap(10105),
                    "D5", long(2525),
                    gap(1265),
                    "G5", long(1262),
                    "D5", long(2525),
                    gap(1264),
                    "G5", long(1262),
                    "D5", long(2525),
                    gap(22738),
                    "D5", long(2525),
                    gap(1264),
                    "G5", long(1262),
                    "D5", long(2525),
                    gap(1265),
                    "G5", long(1262),
                }
            },
            cello => {
                volume: 90,
                once {
                    gap(11368),
                    "G4", long(1262),
                    "G4", long(2525),
                    gap(1264),
                    "G4", long(1262),
                    "G4", long(2525),
                    gap(1265),
                    "G4", long(1262),
                    gap(24001),
                    "G4", long(1262),
                    "G4", long(2525),
                    gap(1265),
                    "G4", long(1261),
                    "G4", long(2525),
                }
            }
        },

        flute {
            metal => {
                volume: 68,
                once {
                    gap(25579),
                    "D5", long(314),
                    "G6", long(314),
                    "Eb6", long(314),
                    "D6", long(157),
                    "Eb6", long(157),
                    "D6", long(157),
                    "C6", long(157),
                    "D6", long(314),
                    "D6", long(314),
                    gap(317),
                    "G5", long(315),
                    "C6", long(157),
                    "B5", long(157),
                    "C6", long(314),
                    "D6", long(314),
                    "Bb5", long(315),
                    "C6", long(315),
                    "G5", long(315),
                    gap(632),
                    "G6", long(315),
                    "Eb6", long(315),
                    "D6", long(157),
                    "Eb6", long(156),
                    "D6", long(156),
                    "C6", long(156),
                    "D6", long(314),
                    "D6", long(315),
                    gap(317),
                    "G5", long(314),
                    "C6", long(156),
                    "B5", long(156),
                    "C6", long(314),
                    "D6", long(315),
                    "Bb5", long(315),
                    "C6", long(314),
                    "G5", long(314),
                    gap(317),
                    "D5", long(315),
                    "G6", long(315),
                    "Eb6", long(314),
                    "D6", long(156),
                    "Eb6", long(156),
                    "D6", long(157),
                    "C6", long(157),
                    "D6", long(315),
                    "D6", long(314),
                    gap(318),
                    "G5", long(314),
                    "C6", long(157),
                    "B5", long(157),
                    "C6", long(315),
                    "D6", long(314),
                    "Bb5", long(314),
                    "C6", long(314),
                    "G5", long(315),
                    gap(633),
                    "G6", long(314),
                    "Eb6", long(315),
                    "D6", long(157),
                    "Eb6", long(157),
                    "D6", long(157),
                    "C6", long(157),
                    "D6", long(314),
                    "D6", long(314),
                    gap(317),
                    "G5", long(315),
                    "C6", long(157),
                    "B5", long(156),
                    "C6", long(314),
                    "D6", long(314),
                    "Bb5", long(315),
                    "C6", long(315),
                    "G5", long(10420),
                    gap(317),
                    "D5", long(314),
                    "G6", long(314),
                    "Eb6", long(315),
                    "D6", long(157),
                    "Eb6", long(157),
                    "D6", long(157),
                    "C6", long(156),
                    "D6", long(314),
                    "D6", long(314),
                    gap(317),
                    "G5", long(315),
                    "C6", long(157),
                    "B5", long(156),
                    "C6", long(314),
                    "D6", long(314),
                    "Bb5", long(315),
                    "C6", long(315),
                    "G5", long(314),
                    gap(633),
                    "G6", long(315),
                    "Eb6", long(315),
                    "D6", long(156),
                    "Eb6", long(156),
                    "D6", long(156),
                    "C6", long(156),
                    "D6", long(315),
                    "D6", long(315),
                    gap(317),
                    "G5", long(314),
                    "C6", long(156),
                    "B5", long(157),
                    "C6", long(315),
                    "D6", long(315),
                    "Bb5", long(314),
                    "C6", long(314),
                    "G5", long(314),
                }
            },
            sfx => {
                volume: 62,
                once {
                    gap(2526),
                    "G4", long(631),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "D5", long(630),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "D5", long(631),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(77),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "D5", long(630),
                    gap(1896),
                    "G4", long(631),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "D5", long(630),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(947),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "D5", long(630),
                    gap(1897),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "D5", long(630),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "D5", long(631),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "D5", long(630),
                    gap(1896),
                    "G4", long(631),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "D5", long(630),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(78),
                    "D5", long(631),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "D5", long(630),
                    gap(1896),
                    "G4", long(631),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "D5", long(630),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "D5", long(631),
                    gap(1896),
                    "G4", long(630),
                    "D5", long(946),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "D5", long(1262),
                    gap(1264),
                    "G4", long(631),
                    "D5", long(946),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(78),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "Eb5", long(77),
                    "D5", long(630),
                }
            }
        },

        start(drums  => beat),
        start(bass   => line),
        start(guitar => riff),
        start(guitar => riff2),
        start(piano  => chords),
        start(piano  => bell),
        start(piano  => wood),
        start(sax    => violin),
        start(sax    => cello),
        start(flute  => metal),
        start(flute  => sfx),

        gap(79683),

        stop(drums  => beat),
        stop(bass   => line),
        stop(guitar => riff),
        stop(guitar => riff2),
        stop(piano  => chords),
        stop(piano  => bell),
        stop(piano  => wood),
        stop(sax    => violin),
        stop(sax    => cello),
        stop(flute  => metal),
        stop(flute  => sfx)
    });

    println!("[INFO] Menyimpan ke gta_sa_theme.wav...");
    save(&lagu, "gta.wav");
    play(&lagu);
    println!("[INFO] Selesai!");
}